### PR TITLE
Initial history

### PR DESCRIPTION
**Pull request by dyladan**
This is all the original history from the dyladan/component-owners repository

### CODE REVIEW

**Comment by dyladan** [comment]
@yurishkuro any idea why there is no CLA check happening on this PR?

**Comment by yurishkuro** [comment]
@lizthegrey @bogdandrutu please configure EasyCLA for this repo

@dyladan please configure this repo per https://github.com/open-telemetry/community/blob/8b0922c1c9f2cbb67f2d4178f4438192e0ff7922/docs/how-to-configure-new-repository.md

**Comment by lizthegrey** [comment]
Getting an infinite spinny from easycla trying to update our repos :/

**Comment by lizthegrey** [comment]
https://github.com/communitybridge/easycla/issues/3145 -- filed ticket, got us on easycla v2, now it'll automatically be enabled on every new repo.

**Review by yurishkuro — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Pull request merged**
